# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qtvBfXxeayQjFtmmrAqNr0TDiTA1oLw#scrollTo=yb4_COOpJLEr
"""

import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as pt
import cv2 #computer vision
from sklearn.model_selection import train_test_split

saldata = pd.read_csv("https://raw.githubusercontent.com/pramodini18/Salary-prediction/refs/heads/master/Salary_Data.csv")
pt.plot(saldata.YearsExperience,saldata.Salary)


X=saldata[['YearsExperience']]
y=saldata['Salary']
X_train, X_test, y_train, y_test = train_test_split(X,y)

X_train

str(len(y_test)/len(y) * 100) + "%" #Testing percentage

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score

iit = LinearRegression()
type(iit)

iit.fit(X_train,y_train)

iit.coef_

pred = iit.predict(X_test) #y prediction

pt.plot(X_test,pred,c="red")

iit.predict([[25]]) #25yrs is input , salary is predicted by the model

#Accuracy Score
from sklearn.metrics import r2_score,mean_squared_error

r2_score(y_test,pred)*100  #accuracy percentage
mean_squared_error(y_test,pred)

#Multiple Linear Regression
usa = pd.read_csv("https://raw.githubusercontent.com/bcbarsness/machine-learning/refs/heads/master/USA_Housing.csv")
usa

usa.info() #Information about the dataframe

usa.columns

X=usa[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population', 'Price']]

y=usa['Price']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=30)  #changing test size

len(X_test)/len(X)

usa_model = LinearRegression()
usa_model.fit(X_train,y_train)

pd.DataFrame(usa_model.coef_,index=X.columns)
usa_model.intercept_
pred_usa=usa_model.predict(X_test)
r2_score(y_test,pred_usa)
